# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studenthub', '0004_auto_20170130_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='acmcontact',
            name='web',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='dancecontact',
            name='web',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='ieeecontact',
            name='web',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='musiccontact',
            name='web',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='quizcontact',
            name='web',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='sankalpcontact',
            name='web',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='theatrecontact',
            name='web',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
