# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studenthub', '0005_auto_20170131_1844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acmcontact',
            name='web',
        ),
        migrations.RemoveField(
            model_name='dancecontact',
            name='web',
        ),
        migrations.RemoveField(
            model_name='ieeecontact',
            name='web',
        ),
        migrations.RemoveField(
            model_name='musiccontact',
            name='web',
        ),
        migrations.RemoveField(
            model_name='quizcontact',
            name='web',
        ),
        migrations.RemoveField(
            model_name='sankalpcontact',
            name='web',
        ),
        migrations.RemoveField(
            model_name='theatrecontact',
            name='web',
        ),
        migrations.AddField(
            model_name='acm',
            name='web',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='dance',
            name='web',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='ieee',
            name='web',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='music',
            name='web',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='quiz',
            name='web',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='sankalp',
            name='web',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='theatre',
            name='web',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
