# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-31 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studenthub', '0006_auto_20170131_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acm',
            name='head1',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='acm',
            name='head2',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='dance',
            name='head1',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='dance',
            name='head2',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='ieee',
            name='head1',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='ieee',
            name='head2',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='music',
            name='head1',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='music',
            name='head2',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='head1',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='head2',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='sankalp',
            name='head1',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='sankalp',
            name='head2',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='theatre',
            name='head1',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='theatre',
            name='head2',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
