# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-31 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studenthub', '0008_auto_20170131_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acmcontact',
            name='phone',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='dancecontact',
            name='phone',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ieeecontact',
            name='phone',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='quizcontact',
            name='phone',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='sankalpcontact',
            name='phone',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='theatrecontact',
            name='phone',
            field=models.TextField(),
        ),
    ]
