# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-06 12:54
from __future__ import unicode_literals

from django.db import migrations, models
import studenthub.models


class Migration(migrations.Migration):

    dependencies = [
        ('studenthub', '0009_auto_20170131_2243'),
    ]

    operations = [
        migrations.CreateModel(
            name='avions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('para1', models.TextField(blank=True)),
                ('para2', models.TextField(blank=True)),
                ('para3', models.TextField(blank=True)),
                ('image1', models.ImageField(blank=True, upload_to=studenthub.models.update_image_name)),
                ('image2', models.ImageField(blank=True, upload_to=studenthub.models.update_image_name)),
                ('head1', models.CharField(blank=True, max_length=120)),
                ('head2', models.CharField(blank=True, max_length=120)),
                ('web', models.CharField(blank=True, max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='avionsContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=125)),
                ('phone', models.TextField()),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='enigma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('para1', models.TextField(blank=True)),
                ('para2', models.TextField(blank=True)),
                ('para3', models.TextField(blank=True)),
                ('image1', models.ImageField(blank=True, upload_to=studenthub.models.update_image_name)),
                ('image2', models.ImageField(blank=True, upload_to=studenthub.models.update_image_name)),
                ('head1', models.CharField(blank=True, max_length=120)),
                ('head2', models.CharField(blank=True, max_length=120)),
                ('web', models.CharField(blank=True, max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='enigmaContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=125)),
                ('phone', models.TextField()),
                ('message', models.TextField()),
            ],
        ),
    ]
